accounts:
  - name: alice
    coins: ["1000Hg", "100000000stake"]
  - name: bob
    coins: ["500Hg"]
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: bob 
  coins: ["5Hg"]
